2014-10-14 17:26:42+0800 [zhidao] ERROR: Obtaining request from start requests
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1192, in run
	    self.mainLoop()
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/Scrapy-0.22.2-py2.7.egg/scrapy/utils/reactor.py", line 41, in __call__
	    return self._func(*self._a, **self._kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/Scrapy-0.22.2-py2.7.egg/scrapy/core/engine.py", line 111, in _next_request
	    request = next(slot.start_requests)
	  File "/home/jihuanli/dabanniu/spider/baiduzhidao/baiduzhidao/spiders/ZhidaoSpider.py", line 63, in start_requests
	    task_json_data = json.loads(task_data)
	  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
	    return _default_decoder.decode(s)
	  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
	    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
	    raise ValueError("No JSON object could be decoded")
	exceptions.ValueError: No JSON object could be decoded
	
2014-10-14 17:27:37+0800 [zhidao] ERROR: Obtaining request from start requests
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1192, in run
	    self.mainLoop()
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/Scrapy-0.22.2-py2.7.egg/scrapy/utils/reactor.py", line 41, in __call__
	    return self._func(*self._a, **self._kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/Scrapy-0.22.2-py2.7.egg/scrapy/core/engine.py", line 111, in _next_request
	    request = next(slot.start_requests)
	  File "/home/jihuanli/dabanniu/spider/baiduzhidao/baiduzhidao/spiders/ZhidaoSpider.py", line 64, in start_requests
	    task_json_data = json.loads(task_data)
	  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
	    return _default_decoder.decode(s)
	  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
	    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
	    raise ValueError("No JSON object could be decoded")
	exceptions.ValueError: No JSON object could be decoded
	
2014-10-14 17:28:21+0800 [zhidao] ERROR: Obtaining request from start requests
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1192, in run
	    self.mainLoop()
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/Scrapy-0.22.2-py2.7.egg/scrapy/utils/reactor.py", line 41, in __call__
	    return self._func(*self._a, **self._kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/Scrapy-0.22.2-py2.7.egg/scrapy/core/engine.py", line 111, in _next_request
	    request = next(slot.start_requests)
	  File "/home/jihuanli/dabanniu/spider/baiduzhidao/baiduzhidao/spiders/ZhidaoSpider.py", line 53, in start_requests
	    conn.request('GET', dest_url)
	  File "/usr/lib/python2.7/httplib.py", line 973, in request
	    self._send_request(method, url, body, headers)
	  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
	    self.endheaders(body)
	  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
	    self._send_output(message_body)
	  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
	    self.send(msg)
	  File "/usr/lib/python2.7/httplib.py", line 791, in send
	    self.connect()
	  File "/usr/lib/python2.7/httplib.py", line 772, in connect
	    self.timeout, self.source_address)
	  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
	    raise err
	socket.error: [Errno 4] Interrupted system call
	
